---

- name: Check FreeIPA client enrollment
  ansible.builtin.stat:
    path: /etc/krb5.keytab
  register: krb5_keytab

- name: Check FreeIPA default.conf
  ansible.builtin.stat:
    path: /etc/ipa/default.conf
  register: ipa_conf

- set_fact:
    postgres_freeipa_enrolled: "{{ ipa_conf.stat.exists and krb5_keytab.stat.exists }}"

- name: Install PostgreSQL packages (RedHat)
  become: true
  ansible.builtin.dnf:
    name: "{{ postgres_packages_redhat }}"
    state: present
  when: ansible_facts.os_family == "RedHat"

- name: Install PostgreSQL packages (Debian)
  become: true
  ansible.builtin.apt:
    name: "{{ postgres_packages_debian }}"
    state: present
    update_cache: true
  when: ansible_facts.os_family == "Debian"

- name: Ensure required locales are available
  become: true
  locale_gen:
    name: "{{ postgres_locale_default }}"
    state: present
  when: ansible_facts.os_family == "Debian"

- name: "include FreeIPA features"
  import_tasks: freeipa.yml
  when: postgres_freeipa and not postgres_is_standby

- name: TLS integration
  when: postgres_tls | bool
  block:
    - include_tasks: "tls_{{ postgres_tls_provider }}.yml"

- name: "set-up primary"
  import_tasks: setup_primary.yml
  when: not postgres_is_standby

- name: "set-up replication"
  import_tasks: setup_replica.yml
  when: postgres_is_standby

- name: Ensure PostgreSQL config is correct
  become: true
  ansible.builtin.template:
    src: postgresql.conf.j2
    dest: "{{ postgres_data_path }}/postgresql.conf"
    owner: postgres
    group: postgres
    mode: '0600'
    setype: postgresql_db_t
  notify:
    - Restart PostgreSQL

- name: Ensure service is set to run automatically
  become: true
  ansible.builtin.systemd:
    name: "{{ postgres_service }}"
    enabled: true
    state: started

- name: Allow remote hosts to connect
  become: true
  ansible.posix.firewalld:
    service: postgresql
    state: enabled
    permanent: true
    immediate: true
    offline: true
  when: postgres_firewalld
