---

- name: check if PostgreSQL has been setup
  become: true
  ansible.builtin.stat:
    path: "{{ postgres_hba_path }}"
  register: postgres_data

- name: "initialize PostgreSQL"
  become: true
  shell: "postgresql-setup initdb"
  when: not postgres_data.stat.exists

- name: "Start PostgreSQL"
  become: true
  ansible.builtin.service:
    name: "{{ postgres_service }}"
    state: started

- name: Ensure replication account exists
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    name: "{{ postgres_replica_user }}"
    password: "{{ postgres_replica_password }}"
    role_attr_flags: "REPLICATION,NOSUPERUSER,NOCREATEROLE,NOCREATEDB"

- name: Ensure standby file is absent
  become: true
  ansible.builtin.file:
    path: "{{ postgres_data_path }}/standby.signal"
    state: absent
  notify:
    - Restart PostgreSQL

- name: allow db connections for replication
  become: true
  community.postgresql.postgresql_pg_hba:
    dest: "{{ postgres_hba_path }}"
    databases: replication
    contype: "{{ postgres_replica_contype }}"
    source: "{{ postgres_replica_source }}"
    method: "{{ postgres_replica_auth }}"
    users: "{{ postgres_replica_user }}"

- name: allow db connections for application servers
  become: true
  community.postgresql.postgresql_pg_hba:
    dest: "{{ postgres_hba_path }}"
    contype: "{{ postgres_app_contype }}"
    source: "{{ postgres_app_source }}"
    method: "{{ postgres_app_method }}"

- name: Ensure PostgreSQL is running
  become: true
  ansible.builtin.systemd_service:
    name: "{{ postgres_service }}"
    state: started
