---

- name: Ensure EPEL is enabled
  become: true
  ansible.builtin.dnf:
    name: epel-release
    state: present

- name: Ensure Podman is available
  become: true
  ansible.builtin.dnf:
    name:
      - podman
    state: present

