---

# Note: host must be enrolled in FreeIPA for this to work!

- name: Ensure required libraries are defined
  become: true
  ansible.builtin.dnf:
    name:
      - python3-cryptography
      - python3-netaddr
      - python3-gssapi
      - python3-ipalib
    state: installed

- name: Check if certificate exists
  stat:
    path: "{{ tls_cert_path }}/{{ freeipa_tls_hostname }}.pem"
  register: cert_status

- stat:
    path: "{{ tls_key_path }}/{{ freeipa_tls_hostname }}.key"
  register: key_status

- name: Generate certificate
  when: not cert_status.stat.exists or not key_status.stat.exists
  become: True
  block:
    - name: Ensure private key for certificate exists
      community.crypto.openssl_privatekey:
        path: "{{ tls_key_path }}/{{ freeipa_tls_hostname }}.key"

    - name: Generate certificate signing request
      community.crypto.openssl_csr:
        return_content: true
        path: "{{ tls_csr_path }}/{{ freeipa_tls_hostname }}.csr"
        privatekey_path: "{{ tls_key_path }}/{{ freeipa_tls_hostname }}.key"
        common_name: "{{ freeipa_tls_hostname }}"
        subject_alt_name:
          - "DNS:{{ freeipa_tls_hostname }}"
      register: freeipa_csr

    - name: Ensure FreeIPA service exists
      freeipa.ansible_freeipa.ipaservice:
        ipaadmin_principal: "{{ podman_ipa_admin_user }}"
        ipaadmin_password: "{{ podman_ipa_admin_pass }}"
        name: "HTTP/{{ freeipa_tls_hostname }}"
        state: present

    - name: Request a certificate from FreeIPA
      freeipa.ansible_freeipa.ipacert:
        ipaadmin_principal: "{{ podman_ipa_admin_user }}"
        ipaadmin_password: "{{ podman_ipa_admin_pass }}"
        state: requested
        csr: "{{ freeipa_csr.csr }}"
        chain: true
        certificate_out: "{{ tls_cert_path }}/{{ freeipa_tls_hostname }}.pem"
        principal: HTTP/{{ freeipa_tls_hostname }}
      register: freeipa_cert
  always:
    - name: Ensure csr is cleaned up
      ansible.builtin.file:
        path: "{{ tls_csr_path }}/{{ freeipa_tls_hostname }}.csr"
        state: absent
