---

# engine type
traefik_engine: "podman"
traefik_podman_socket: "{{ podman_socket | default('/run/podman/podman.sock') }}"

# firewalld integration
traefik_manage_firewalld: true

# traefik oci image
traefik_tag: "latest"
traefik_image: "docker.io/library/traefik:{{traefik_tag}}"
traefik_service: "traefik"
traefik_network: "{{ traefik_service }}"

# extra services
traefik_dashboard: false

# directories
traefik_dir: "/srv/podman/{{ traefik_service }}"
traefik_dir_dynamic: "{{ traefik_dir }}/dynamic"
traefik_conf: "{{ traefik_dir }}/traefik.yml"

traefik_systemd_dir: "/etc/systemd/system"
traefik_tls_dir: "/etc/pki/tls/private"

# http (web)
traefik_http: true
traefik_http_socket: "http.socket"
traefik_http_path: "{{ traefik_systemd_dir }}/{{ traefik_http_socket }}"
traefik_http_proxies:
  - 172.0.0.1/32
  - 192.168.0.0/16
  - 127.16.0.0/12
  - 10.0.0.0/8

# https (websecure)
traefik_https: true
traefik_https_socket: "https.socket"
traefik_https_path: "{{ traefik_systemd_dir}}/{{ traefik_https_socket }}"
traefik_https_proxies: "{{ traefik_http_proxies }}"

# TLS integration
#traefik_https_provider: ""
traefik_https_hostname: "{{ inventory_hostname }}"
traefik_https_certificates:
  - hostname: "{{ traefik_https_hostname }}"

# admin account for interacting with freeipa (if enabled)
traefik_ipa_admin_user: "{{ ipaadmin_principal|default('admin') }}"
traefik_ipa_admin_pass: "{{ ipaadmin_password }}"

# core volumes
traefik_bind_https: "/etc/traefik/certs"

traefik_volumes_base:
  - "{{ traefik_conf }}:/etc/traefik/traefik.yml:Z"
  - "{{ traefik_dir_dynamic }}:/etc/traefik/dynamic:Z,ro"
  - "{{ traefik_podman_socket }}:/var/run/docker.sock"

traefik_volumes_tls:
  - "{{ traefik_tls_dir }}:{{ traefik_bind_https }}:ro"

# extension points
traefik_extra_volumes: []
