---

# engine type
traefik_engine: "podman"
traefik_podman_socket: "{{ podman_socket | default('/run/podman/podman.sock') }}"

# traefik oci image
traefik_tag: "latest"
traefik_image: "docker.io/library/traefik:{{traefik_tag}}"
traefik_service: "traefik"
traefik_network: "{{ traefik_service }}"

# extra services
traefik_dashboard: false

# directories
traefik_dir: "/srv/podman/{{ traefik_service }}"
traefik_conf: "{{ traefik_dir }}/traefik.yml"

traefik_systemd_dir: "/etc/systemd/system"
traefik_tls_dir: "/etc/pki/tls/"

# http (web)
traefik_http: true
traefik_http_socket: "http.socket"
traefik_http_path: "{{ traefik_systemd_dir }}/{{ traefik_http_socket }}"
traefik_http_proxies:
  - 127.0.0.1/32
  - 192.168.0.0/16
  - 127.16.0.0/12
  - 10.0.0.0/8

# https (websecure)
traefik_https: true
traefik_https_socket: "https.socket"
traefik_https_path: "{{ traefil_systemd_dir}}/{{ traefik_https_socket }}"
traefik_https_proxies: "{{ traefik_http_proxies }}"

# TLS integration
traefik_https_provider: "none"
traefik_https_hostname: "{{ ansible_host }}"
traefik_https_principal: "host/{{ traefik_https_hostname }}"
traefik_https_alts:
  - "DNS:{{ traefik_https_hostname }}"

# admin account for interacting with freeipa (if enabled)
traefik_ipa_admin_user: "{{ ipaadmin_principal|default('admin') }}"
traefik_ipa_admin_pass: "{{ ipaadmin_password }}"

# TLS paths
traefik_tls_cert: "{{ traefik_tls_dir }}/certs/{{ traefik_https_hostname }}.pem"
traefik_tls_key: "{{ traefik_tls_dir }}/private/{{ traefik_https_hostname }}.key"
traefik_tls_csr: "{{ traefik_tls_dir }}/misc/{{ traefik_https_hostname }}.csr"
