---

- name: Ensure container exists
  become: true
  containers.podman.podman_container:
    name: "{{ valkey_service }}"
    image: "{{ valkey_image }}"
    state: quadlet
    quadlet_dir: "{{ valkey_systemd_dir }}"
    healthcheck: "CMD-SHELL valkey-cli ping | grep PONG"
    healthcheck_interval: 1s
    healthcheck_timeout: 3s
    healthcheck_retries: 5
    healthcheck_start_period: 3s
    network:
      - "{{ valkey_network }}"
  notify:
    - Restart valkey
