---
postgres_data_path: /var/lib/pgsql/data
postgres_hba_path: "{{ postgres_data_path }}/pg_hba.conf"

postgres_packages_redhat:
  - postgresql-server
  - postgresql-contrib
  - python3-psycopg2
  - acl
  - glibc-langpack-en

postgres_packages_debian:
  - postgresql
  - postgresql-contrib
  - python3-psycopg2

postgres_is_standby: false
postgres_replica_user: rep_ha

# locales
postgres_timezone: "Europe/London"

postgres_locale_default: "en_GB.UTF-8"
postgres_locale_messages: "{{ postgres_locale_default }}"
postgres_locale_money: "{{ postgres_locale_default }}"
postgres_locale_numeric: "{{ postgres_locale_default }}"
postgres_locale_time: "{{ postgres_locale_default }}"

# manage firewall
postgres_firewalld: true

# freeipa integration
postgres_freeipa: false
postgres_freeipa_realm: ""
postgres_gss_service: "postgres/{{ inventory_hostname }}"
postgres_keytab: "{{ postgres_data_path }}/pg.keytab"

postgres_manage_net: "192.168.1.0/24"
