---

- name: Ensure proxy network exists
  become: true
  containers.podman.podman_network:
    name: "{{ traefik_network }}"
    state: quadlet

- name: Ensure proxy data directory exists
  become: true
  ansible.builtin.file:
    state: directory
    name: "{{ traefik_dir }}"

- name: Ensure configuration file exists
  become: true
  ansible.builtin.template:
    src: "traefik.yml.j2"
    dest: "{{ traefik_conf }}"
  notify:
    - Restart traefik

- name: Ensure http socket exists
  become: true
  ansible.builtin.template:
    src: "socket.j2"
    dest: "{{ traefik_http_path }}"
  vars:
    socket_port: 80
    socket_fd: web
  when: podman_traefik_http
  notify:
    - Restart traefik

- name: Ensure http socket does not exist
  become: true
  ansible.builtin.file:
    state: absent
    path: "{{ traefik_http_path }}"
  when: not podman_traefik_http

- name: Ensure https socket exists
  become: true
  ansible.builtin.template:
    src: "socket.j2"
    dest: "{{ traefik_https_path }}"
  vars:
    socket_port: 443
    socket_fd: websecure
  when: podman_traefik_https
  notify:
    - Restart traefik

- name: Ensure https socket does not exist
  become: true
  ansible.builtin.file:
    state: absent
    path: "{{ traefik_https_path }}"
  when: not podman_traefik_https

- name: Ensure proxy container exists
  become: true
  containers.podman.podman_container:
    name: "{{ traefik_service }}"
    image: "{{ traefik_image }}"
    state: quadlet
    volumes:
      - "{{ traefik_conf }}:/etc/traefik/traefik.yml:Z"
      - "{{ traefik_podman_socket }}:/var/run/docker.sock"
    network:
      - "{{ traefik_network }}.network"
    quadlet_options:
      - "SecurityLabelDisable=true"
      - "NoNewPrivileges=true"
      - "ReadOnly=true"
      - "Notify=true"
      - |
        [Unit]
        Requires=podman.socket
        After=podman.socket
  notify:
    - Restart traefik

- name: Ensure http socket service is enabled
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: "{{ traefik_http_socket }}"
    enabled: true
  when: traefik_http

- name: Ensure podmans socket service is enabled
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: "{{ traefik_https_socket }}"
    enabled: true
  when: traefik_https
