---

- name: "Reverse proxy configuration"
  import_tasks: "engine_{{ traefik_engine }}.yml"
  when: traefik_engine is defined

- name: "TLS provider integration"
  include_tasks: "tls_{{ traefik_https_provider }}.yml"
  when: traefik_https_provider is defined and traefik_https_provider | length > 0

- name: Firewalld integration
  ansible.builtin.include_tasks: firewalld.yml
  when: traefik_manage_firewalld | bool
