---

# Note: host must be enrolled in FreeIPA for this to work!

- name: Ensure required libraries are defined
  become: true
  ansible.builtin.dnf:
    name:
      - python3-cryptography
      - python3-netaddr
      - python3-gssapi
      - python3-ipalib
    state: installed

- name: Ensure IPA HTTP services exist
  freeipa.ansible_freeipa.ipaservice:
    ipaadmin_principal: "{{ traefik_ipa_admin_user }}"
    ipaadmin_password: "{{ traefik_ipa_admin_pass }}"
    name: "HTTP/{{ item.hostname }}"
    host: "{{ traefik_https_hostname }}"
    skip_host_check: true
  loop: "{{ traefik_https_certificates }}"

- name: Generate certificates
  ansible.builtin.include_tasks: cert_freeipa.yml
  loop: "{{ traefik_https_certificates }}"
  loop_control:
    loop_var: cert
    label: "{{ cert.hostname }}"

- name: Ensure tls configuration file exists
  become: true
  ansible.builtin.template:
    src: "tls.yml.j2"
    dest: "{{ traefik_dir_dynamic }}/tls.yml"
  notify:
    - Restart traefik
